name: Build filterlists

on:
  schedule:
  - cron: "0 17 * * *"

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Download repo
      uses: actions/checkout@v2

    - name: Download dependencies
      run: |
        go get -v -t -d ./...
      
    - name: Runnning build/generation script
      shell: bash
      run: |
        go run main.go
      working-directory: generator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_REPO_OWNER: xarantolus
        INITIAL_REPO_NAME: filtrite
        OUTPUT_FILE: filterlists_jsonp.js

    - name: Generate tag name
      run: echo "TAG_NAME=$(date +%F-%H-%M)" >> $GITHUB_ENV  

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: generator/filterlists_jsonp.js
        name: Automatic generation
        tag_name: ${{ env.TAG_NAME }}
        body: "This release contains the latest data for use in the web application. Not really interesting :)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 2
        delete_tags: true 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
