name: Build Vue WebApp

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2

    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'xarantolus'
        reponame: 'filtrite-lists'
        token: ${{ secrets.GITHUB_TOKEN }}
      working-directory: filtrite-search
