name: Build Vue WebApp

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2

    - name: "Prepare repo for Vue build"
      run: |
        TMP_DIR="$(mktemp -d)"
        cp -r filtrite-search/* "$TMP_DIR"
        rm -rf *
        cp -r $TMP_DIR/* .

    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'xarantolus'
        reponame: 'filtrite-lists'
        cname: 'filterlists.010.one'
        token: ${{ secrets.GITHUB_TOKEN }}
